global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'node-app'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['app:3000']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
